hal2024HOLO-ME/holome

Assets/HOLOMEProject/Script/CollisionDetection/FoodCollisionDetection.cs
Assets/HOLOMEProject/Script/FbxLoader.cs
Assets/Scenes/ObjectCheck.unity
ProjectSettings/ProjectSettings.asset

タヌキの正面方向を調整

---

Assets/HOLOMEProject/Script/Photon.meta
Assets/HOLOMEProject/Script/Photon/AvatarController.cs
Assets/HOLOMEProject/Script/Photon/AvatarController.cs.meta
Assets/HOLOMEProject/Script/Photon/Matching.cs
Assets/HOLOMEProject/Script/Photon/Matching.cs.meta
Assets/HOLOMEProject/animation/Mii Animator Controller.controller
Assets/Resources/Avatar.prefab
Assets/Resources/Avatar.prefab.meta
Assets/Resources/animation/Holo Animator Controller.controller
Assets/Scenes/PhotonTest.unity
Assets/Scenes/PhotonTest.unity.meta

Photonルーム参加できるようにした。
ルーム検索その他もろもろ

add：Photon動作チェック

---

Assets/HOLOMEProject/Script/ControlPanel/ChangeTarget.cs
Assets/HOLOMEProject/Script/ControlPanel/ChangeTarget.cs.meta
Assets/HOLOMEProject/Script/ControlPanel/ColorChanger.cs
Assets/HOLOMEProject/Script/ControlPanel/ColorChanger.cs.meta
Assets/Scenes/ShowCharacterScene.unity
Assets/XR/UserSimulationSettings/SimulationEnvironmentAssetsManager.asset

add: 色の追加とカスタマイズまで

---

Assets/Scenes/ShowCharacterScene.unity

シャワーの修正(多分治ってるはず)

---

Assets/HOLOMEProject/Script/Photon/Matching.cs
Assets/Scenes/PhotonTest.unity

ルーム参加時のペットの座標をMainCameraから半径1メートルにスポーンさせたい

add：ルーム参加時の座標設定

---

Assets/HOLOMEProject/Script/PersonalityDiagnosis/ShowCharacter.cs
Assets/Scenes/ShowCharacterScene.unity
ProjectSettings/ProjectSettings.asset

add: デフォルトのキャラクターを設定

---

.github/workflows/approve.yml

- #50 
- 動画撮影のために今回だけ。。。基本はやらない

add: PRスキップ用ci

---

Assets/HOLOMEProject/Script/ControlPanel/DecorationsController.cs
Assets/HOLOMEProject/Script/ControlPanel/DecorationsController.cs.meta
Assets/Scenes/ShowCharacterScene.unity
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/ProjectSettings.asset

#46 　アクセサリーカスタマイズの諸々の実装
#56  ついでに位置ずらした(実機見て随時修正)
#45 アイコン系まだなので
discordにて

add:アイテムカスタマイズの実装

---

Assets/HOLOMEProject/Script/PersonalityDiagnosis/ShowCharacter.cs

add: バックエンドから取得した値でキャラクタを表示する

---

Assets/Scenes/ShowCharacterScene.unity
Assets/XR/UserSimulationSettings/SimulationEnvironmentAssetsManager.asset

#64 白とグレーの差が無かったので変更
#64 狐で来てから変更する色が出てくる
discord

fix: カスタマイズの白とグレー色差をつけた

---

Assets/HOLOMEProject/Object/brush.fbx.meta
Assets/HOLOMEProject/Script/CollisionDetection/BrushCollisionDetection.cs
Assets/HOLOMEProject/Script/CollisionDetection/BrushCollisionDetection.cs.meta
Assets/HOLOMEProject/Script/ControlPanel/ShowBrush.cs
Assets/HOLOMEProject/Script/ControlPanel/ShowBrush.cs.meta
Assets/HOLOMEProject/Script/FbxLoader.cs
Assets/Scenes/ShowCharacterScene.unity
ProjectSettings/ProjectSettings.asset

- #52 
- #69 
https://github.com/hal2024HOLO-ME/holome/assets/80617274/c81f6968-f72d-4f00-8af8-6d2ea9bbe699

add: brush機能

---

Assets/HOLOMEProject/Script/Auth/Login.cs
Assets/HOLOMEProject/Script/Auth/Register.cs
Assets/Scenes/LoginScene.unity
Assets/Scenes/RegisterScene.unity

add: ログインのときにメールアドレスからユーザーIDにする

---

Assets/HOLOMEProject/Script/Auth/MoveToLoginScene.cs
Assets/HOLOMEProject/Script/Auth/Register.cs
Assets/HOLOMEProject/Script/PersonalityDiagnosis/SendResult.cs

fix: これないとコンパイルerrorでる

---

Assets/HOLOMEProject/Script/Auth/Login.cs
Assets/HOLOMEProject/Script/PersonalityDiagnosis/ChangeToCharacterNameSlate.cs
Assets/HOLOMEProject/Script/PersonalityDiagnosis/ChangeToCharacterNameSlate.cs.meta
Assets/HOLOMEProject/Script/PersonalityDiagnosis/SendCharacterName.cs
Assets/HOLOMEProject/Script/PersonalityDiagnosis/SendCharacterName.cs.meta
Assets/HOLOMEProject/Script/PersonalityDiagnosis/SendResult.cs
Assets/Scenes/PersonalityDiagnosis.unity
ProjectSettings/ProjectSettings.asset

- #83 
- 次回ログインのときも考えた実装
discordにまとめました

add: パートナーの名前を入力できるようにする

---

Assets/Scenes/LoginScene.unity
Assets/Scenes/PersonalityDiagnosis.unity
Assets/Scenes/RegisterScene.unity
Assets/Scenes/TopScene.unity

add: バツボタンを削除する

---

Assets/HOLOMEProject/Script/PersonalityDiagnosis/ShowCharacter.cs
Assets/HOLOMEProject/Script/Utility/Gif/AnimatedImage.cs
Assets/Scenes/ShowCharacterScene.unity

add: ローディング後診断結果のモデルに対応するローディングを表示する

---

Assets/Scenes/ShowCharacterScene.unity
ProjectSettings/ProjectSettings.asset

add: 操作パネルをいい感じにする

---

Assets/HOLOMEProject/Script/CollisionDetection/FoodCollisionDetection.cs
Assets/HOLOMEProject/Script/FbxLoader.cs
Assets/HOLOMEProject/Script/PersonalityDiagnosis/ShowCharacter.cs
Assets/Resources/TanukiVerGhost.prefab
Assets/Resources/TanukiVerGhost.prefab.meta
Assets/Resources/animation/TanukiVerGhost Animator Controller.controller
ProjectSettings/ProjectSettings.asset

add: Photonのガチャコン

---

Assets/Resources/CatVerGhost.prefab
Assets/Resources/CatVerGhost.prefab.meta
Assets/Resources/CatVerNormal.prefab
Assets/Resources/CatVerNormal.prefab.meta
Assets/Resources/MiiVerGhost.prefab
Assets/Resources/MiiVerGhost.prefab.meta
Assets/Resources/MiiVerNormal.prefab
Assets/Resources/MiiVerNormal.prefab.meta
Assets/Resources/TanukiVerNormal.prefab
Assets/Resources/TanukiVerNormal.prefab.meta

Photon用のキャラobjectの追加

---

Assets/HOLOMEProject/Script/CollisionDetection/ShowerCollisionDetection.cs
Assets/HOLOMEProject/Script/CollisionDetection/ShowerCollisionDetection.cs.meta
Assets/HOLOMEProject/Script/ControlPanel/ShowShower.cs
Assets/HOLOMEProject/Script/FbxLoader.cs
Assets/HOLOMEProject/animation/Script/ShowerControl.cs
Assets/Scenes/ShowCharacterScene.unity
ProjectSettings/ProjectSettings.asset

#98  機能的にはできた。基本はブラシに合わせてる。修正箇所あり。
#108 シャワーのみ
・ついでにブラシの大きさと向き変えた
・使ってないやつ消した(using System.Collections.Generic;とか)
#108  シャワー再びだすと勝手に水流れる修正
・public static bool isShowerUsed 、HandleCollisionクラスはいるとfalseになるところ
動画discord

シャワーの当たり判定

---

Assets/HOLOMEProject/Script/PersonalityDiagnosis/ShowCharacter.cs
Assets/HOLOMEProject/Script/Utility/Gif/AnimatedTextures.cs
Assets/Scenes/ShowCharacterScene.unity
Assets/Scenes/TopScene.unity
ProjectSettings/EditorBuildSettings.asset

[実機で確認後レビューしてほしい]　fix: HololendsでCanvas見れなかったので別の方法にした

---

Assets/HOLOMEProject/Script/FbxLoader.cs

キャラ出力時の座標を編集

---

Assets/HOLOMEProject/Utilities/Mesh.meta
Assets/HOLOMEProject/Utilities/Mesh/SpatialMesh.prefab
Assets/HOLOMEProject/Utilities/Mesh/SpatialMesh.prefab.meta
Assets/Resources/TanukiVerNormal.prefab
Assets/Scenes/ShowCharacterScene.unity
Assets/XR/UserSimulationSettings/SimulationEnvironmentAssetsManager.asset
ProjectSettings/ProjectSettings.asset

#120 Meshで空間認識
・MeshtestObjectに重力テスト用入ってます。
実機でないと確認できないので省略

add: MeshMap

---

Assets/HOLOMEProject/Script/ControlPanel/ShowFood.cs
Assets/HOLOMEProject/animation/Food Animator Controller.controller

feat: フードの表示切替

---

Assets/HOLOMEProject/Script/FbxLoader.cs
ProjectSettings/ProjectSettings.asset

fix: Gif出すときの秒数設定と動的にモデル出す

---

Assets/Scenes/ShowCharacterScene.unity

fix: 上部のアイコンついてなかった

---

Assets/Resources/CatVerGhost.prefab
Assets/Resources/CatVerNormal.prefab

#160  ねこゴースト、目と耳が表示されてなかったのを表示

fix: ねこゴースト表示切替

---

Assets/Scenes/TopScene.unity
ProjectSettings/ProjectSettings.asset

add: 遊び方パネル

---

Assets/HOLOMEProject/Script/ControlPanel/DecorationsController.cs

#164 妖怪かノーマルかの判定
#159 妖怪の時マフラーをスカーフにした
discord

add: アクセサリーに妖怪の判定いれた

---

Assets/HOLOMEProject/Script/FbxLoader.cs
Assets/Resources/CatVerGhost.prefab
Assets/Scenes/ShowCharacterScene.unity

- #157 
RigidBody、ObjectManupulation、BoxCollider追加
discord

add: ローディング後のパートナー出てくるときに机にだす。

---

Assets/Resources/CatVerGhost.prefab

add: catにbox colliderなどを追加

---

Assets/Resources/MiiVerGhost.prefab

fix: mufflerのスペルミス

---

Assets/HOLOMEProject/Script/ControlPanel/DecorationsController.cs
Assets/XR/UserSimulationSettings/SimulationEnvironmentAssetsManager.asset

#179 ミィゴーストは他の妖怪と違ってマフラーなのでその判定
mufflerがmafflerになっていたのでモデル修正き次第正常か確認する
discord

fix: ミィ妖怪はノーマルと同じアイテム判定

---

Assets/HOLOMEProject/Script/Test.cs
Assets/HOLOMEProject/Script/Test.cs.meta
Assets/Scenes/ToyTest.unity
Assets/Scenes/ToyTest.unity.meta

objectを追いかけるようにした
object同士がぶつかっても止まらない。。。

objectを追いかけるようにした

---

Assets/HOLOMEProject/Script/CO.cs
Assets/HOLOMEProject/Script/CollisionDetection/BrushCollisionDetection.cs
Assets/HOLOMEProject/Script/FbxLoader.cs
Assets/Resources/CatVerGhost.prefab
Assets/Resources/MiiVerGhost.prefab
Assets/Scenes/ShowCharacterScene.unity

- #177 
- #186 186
- オブジェクトのmassを１０に変更。

fix: ブラシ修正

---

Assets/HOLOMEProject/Script/Auth/GetCharacterJson.cs
Assets/HOLOMEProject/Script/Auth/GetCharacterJson.cs.meta
Assets/HOLOMEProject/Script/Auth/Login.cs
Assets/HOLOMEProject/Script/Auth/Register.cs
Assets/HOLOMEProject/Script/Auth/SignOut.cs
Assets/HOLOMEProject/Script/Auth/SignOut.cs.meta
Assets/HOLOMEProject/Script/Auth/types/CharacterData.cs
Assets/HOLOMEProject/Script/Auth/types/CharacterData.cs.meta
Assets/HOLOMEProject/Script/Auth/types/LoginResponse.cs
Assets/HOLOMEProject/Script/Auth/types/LoginResponse.cs.meta
Assets/HOLOMEProject/Script/ControlPanel/ChangeTarget.cs
Assets/HOLOMEProject/Script/ControlPanel/ColorChanger.cs
Assets/HOLOMEProject/Script/ControlPanel/DecorationsController.cs
Assets/HOLOMEProject/Script/FbxLoader.cs
Assets/HOLOMEProject/Script/PersonalityDiagnosis/SendCharacterName.cs
Assets/HOLOMEProject/Script/PersonalityDiagnosis/SendResult.cs
Assets/Scenes/ShowCharacterScene.unity
Assets/XR/UserSimulationSettings/SimulationEnvironmentAssetsManager.asset

add: サインアウト時にJSON保存。キャラクターを持っていたらShowCharacterSceneに遷移

---

Assets/Resources/CatVerGhost.fbx.meta
Assets/Resources/CatVerGhost.prefab
Assets/Resources/CatVerGhost.prefab.meta

add: catGhost

---

Assets/HOLOMEProject/Script/Auth/GetCharacterJson.cs
Assets/HOLOMEProject/Script/Auth/Login.cs
Assets/HOLOMEProject/Script/FbxLoader.cs

feat: キャラがいるときにはカスタマイズを行う

---

Assets/Resources/CatVerGhost.fbx.meta
Assets/Resources/CatVerGhost.prefab
Assets/Resources/CatVerGhost.prefab.meta

fix: 赤い耳つけた

---

Assets/HOLOMEProject/Script/CollisionDetection/FoodCollisionDetection.cs
Assets/Resources/CatVerGhost.prefab
Assets/Resources/MiiVerGhost.prefab

add:ご飯を食べる修正

---

Assets/HOLOMEProject/Script/HealthMonitor.cs

fix: datetimeから時間を取得

---

Assets/HOLOMEProject/Script/FbxLoader.cs
Assets/HOLOMEProject/Script/Utility/Gif/AnimatedTextures.cs
Assets/HOLOMEProject/Utilities/Mesh/SpatialMesh.prefab
Assets/Resources/CatVerGhost.prefab
Assets/Resources/MiiVerGhost.prefab
Assets/Scenes/LoginScene.unity
Assets/Scenes/PersonalityDiagnosis.unity
Assets/Scenes/RegisterScene.unity
Assets/Scenes/ShowCharacterScene.unity
Assets/Scenes/TopScene.unity
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/ProjectSettings.asset

add: プレゼンしたときのデータ。これをmergeすると食べる動かない

---

Assets/HOLOMEProject/Script/ControlPanel/ShowBall.cs
Assets/HOLOMEProject/Script/ControlPanel/ShowBall.cs.meta
Assets/Scenes/ShowCharacterScene.unity

#193
ボタン押し直したら非表示になるところ
discord

add: ボールの追加

---

Assets/HOLOMEProject/Script/PersonalityDiagnosis/SendCharacterName.cs
Assets/HOLOMEProject/Script/PersonalityDiagnosis/ShowCharacter.cs

add: キャラクターにつけた名前を保存する変数追加

---

Assets/HOLOMEProject/Script/FbxLoader.cs
Assets/HOLOMEProject/Script/MySpeechRecognizer.cs
Assets/Scenes/speech-test.unity
ProjectSettings/ProjectSettings.asset

feat: 音声によって移動させる

---

Assets/Resources/CatVerGhost.prefab
Assets/Resources/CatVerNormal.fbx.meta
Assets/Resources/CatVerNormal.prefab
Assets/Resources/DogVerGhost.fbx.meta
Assets/Resources/DogVerGhost.prefab
Assets/Resources/DogVerNormal.fbx.meta
Assets/Resources/DogVerNormal.prefab
Assets/Resources/KitsuneVerGhost.fbx.meta
Assets/Resources/KitsuneVerGhost.prefab
Assets/Resources/KitsuneVerNormal.fbx.meta
Assets/Resources/KitsuneVerNormal.prefab
Assets/Resources/TanukiVerGhost.fbx.meta
Assets/Resources/TanukiVerGhost.prefab
Assets/Resources/TanukiVerNormal.fbx.meta
Assets/Resources/TanukiVerNormal.prefab

add: animatorとbox colliderを追加

---

Assets/HOLOMEProject/Script/PersonalityDiagnosis/SendResult.cs

fix: ログインしないためのエンドポイントを叩く

---

Assets/HOLOMEProject/Script/ControlPanel/DecorationsController.cs
Assets/HOLOMEProject/Script/PersonalityDiagnosis/SendResult.cs
Assets/Resources/MiiVerNormal.prefab
ProjectSettings/ProjectSettings.asset

#217 追加後の修正
#219
characterParentObject1がNull固定されていたため修正
discord

fix: Miiノーマル適用時のカスタマイズ調整

---

Assets/HOLOMEProject/Script/AnimatorChack.cs
Assets/HOLOMEProject/Script/AnimatorChack.cs.meta
Assets/HOLOMEProject/Script/CO.cs
Assets/Resources/KitsuneVerGhost.prefab
Assets/Resources/MiiVerNormal.prefab
Assets/Scenes/animator-chack.unity
Assets/Scenes/animator-chack.unity.meta

add: animation test

---

Assets/Resources/MiiVerNormal.fbx.meta
Assets/Resources/MiiVerNormal.prefab

add: MiiVerNormalにanimtorを追加

---

Assets/Resources/CatVerGhost.prefab
Assets/Resources/CatVerNormal.prefab
Assets/Resources/DogVerGhost.prefab
Assets/Resources/DogVerNormal.prefab
Assets/Resources/KitsuneVerGhost.prefab
Assets/Resources/KitsuneVerNormal.prefab
Assets/Resources/MiiVerGhost.prefab
Assets/Resources/TanukiVerGhost.prefab
Assets/Resources/TanukiVerNormal.prefab

add: iskinematicのチェックを外す

---

Assets/Resources/CatVerGhost.prefab
Assets/Resources/CatVerNormal.prefab
Assets/Resources/DogVerGhost.prefab
Assets/Resources/DogVerNormal.prefab
Assets/Resources/KitsuneVerGhost.prefab
Assets/Resources/KitsuneVerNormal.prefab
Assets/Resources/MiiVerGhost.prefab
Assets/Resources/MiiVerNormal.prefab
Assets/Resources/TanukiVerGhost.prefab
Assets/Resources/TanukiVerNormal.prefab
Assets/Scenes/TopScene.unity
ProjectSettings/ProjectSettings.asset

add: iskinematicのチェックを付ける
